### ISSUE TITLE
Pose with Covariance?

### ISSUE THREAD

**Issue by MrOCW** [rsasaki0109/pcl_localization_ros2#11]
Hi, are there plans to calculate the covariance matrices for the pose output? Would be really helpful for fusing the output with other sensors. Thanks!

**Comment by rsasaki0109** [comment]
Covariance output for scan matching is still in the research phase and we have no plans to implement it at this time.
Any good ideas are welcome.

**Comment by rsasaki0109** [comment]
I have read various papers and found nothing that looked good that I could implement, so I am closing this issue for now.
Please open this again if you have any good ideas.
