### ISSUE TITLE
IMU Calibration

### ISSUE THREAD

**Issue by CtPeng-USTC-ND** [rsasaki0109/pcl_localization_ros2#13]
Thanks for your valuable work!

Currently, I am using the lidar undistortion function and embedding it into hdl_localization. However, when I turned IMU on and played my bag, the localization failed. I'm wondering if it's a problem with IMU calibration, have you done the calibration in the function (I didn't find the interface for setting the IMU parameters)?

**Comment by rsasaki0109** [comment]
The lidar undistortion function in this package is based on LeGO-LOAM, so if you are not using the LiDAR with built-in IMU, you need to implement tf yourself.

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM

**Comment by CtPeng-USTC-ND** [comment]
> 

Many thanks!

**Comment by rsasaki0109** [comment]
I would like to implement this conversion at some point, so I will reopen this issue once so I don't forget.

**Comment by CtPeng-USTC-ND** [comment]
Got it. Looking forward to the new version, thanks.

**Comment by rsasaki0109** [comment]
https://github.com/rsasaki0109/pcl_localization_ros2/pull/17
