### ISSUE TITLE
The link to download the bag is not working

### ISSUE THREAD

**Issue by pavneet9** [rsasaki0109/pcl_localization_ros2#15]
Hi,

Looks like the link for the bag is not working can you provide the same.

**Comment by rsasaki0109** [comment]
The rosbag and map used were published openly and I am not the provider of rosbag, I cannot provide the same.
If you need them, please contact the provider.

I will make changes in time regarding the sample data in this package.

**Comment by rsasaki0109** [comment]
The following package can be used to convert any ros1 rosbag to ros2.

https://gitlab.com/MapIV/rosbags

**Comment by rsasaki0109** [comment]
I'm sorry. It is difficult for me to prepare sample rosbag and pcd by myself, so please respond above. This issue is now closed.
