### ISSUE TITLE
map data

### ISSUE THREAD

**Issue by whuzs** [rsasaki0109/pcl_localization_ros2#3]
hello, could you share map data? bin_tc-2017-10-15-ndmap.pcd

**Comment by rsasaki0109** [comment]
There is also a pcd file on the site with rosbag.

**Comment by whuzs** [comment]
do you mean this site: https://data.tier4.jp/rosbag_details/?id=212 ?  this only have rosbag!

**Comment by rsasaki0109** [comment]
Once you log in, you will also see a link to the pcd file.

**Comment by whuzs** [comment]
thank you!

**Comment by Alex-Beh** [comment]
@rsasaki0109 Hi, thanks for the great project. I have created the account but cannot find neither the rosbag nor the pcd file. Is the website structure changed already?

**Comment by rsasaki0109** [comment]
This is a good reference for you. Please use other open data.
https://github.com/rsasaki0109/pcl_localization_ros2/issues/15
