### ISSUE TITLE
Unable to compile on Galactic

### ISSUE THREAD

**Issue by MrOCW** [rsasaki0109/pcl_localization_ros2#9]
Hi, attempting `colcon build --symlink-install` returns:
```
pcl_localization_ros2/src/pcl_localization_component.cpp: In member function ‘virtual CallbackReturn PCLLocalization::on_activate(const rclcpp_lifecycle::State&)’:
pcl_localization_ros2/src/pcl_localization_component.cpp:80:42: error: no matching function for call to ‘rclcpp_lifecycle::LifecyclePublisher<sensor_msgs::msg::PointCloud2_<std::allocator<void> > >::publish(sensor_msgs::msg::PointCloud2_<std::allocator<void> >::SharedPtr&)’
   80 |     initial_map_pub_->publish(map_msg_ptr);
```

**Comment by rsasaki0109** [comment]
This package is only tested and supported up to ros2 foxy. (I do hope to get ros2 humble support eventually.)
Perhaps ros2 galctic has had a major change in the rclcpp API.

**Comment by Markurt** [comment]
I also met the same issue when trying to compile on Foxy. do you have any idea now? @MrOCW

**Comment by MrOCW** [comment]
@Markurt I made some minor edits to load a pcd, it is working for me now.

**Comment by rsasaki0109** [comment]
Sorry, I only tested this package with dashing...

**Comment by Markurt** [comment]
> @Markurt I made some minor edits to load a pcd, it is working for me now.

I modified the pcl_localization_component.cpp:80 from `initial_map_pub_->publish(map_msg_ptr);` to `initial_map_pub_->publish(*map_msg_ptr);` and now I can successfully build, but when I try to launch, I cannot visualize the PCD map in Rviz until I launch again. May I know that if you meet the similiar problem before?

**Comment by rsasaki0109** [comment]
Added support for foxy.
The problem with pcd not being visible was because param was not being read correctly and pcd was not being published.

PR
https://github.com/rsasaki0109/pcl_localization_ros2/pull/10

**Comment by rsasaki0109** [comment]
The issue has been resolved, so close this issue.
